Vet clinic database: query and update animals table
RashidMenhas/Vet_clinic pull request #2
Opened 2023-01-05 21:06 UTC by RashidMenhas

- Use database transactions.
- Modify and delete data in SQL.

![c1](https://user-images.githubusercontent.com/108628726/210952308-92b14fb5-65d2-4cf3-af97-41189ba784d0.png)
![c2](https://user-images.githubusercontent.com/108628726/210952363-92b24dbd-20f5-46e9-94b1-705963849a9d.png)
![c2 1](https://user-images.githubusercontent.com/108628726/210952391-a6680720-5541-45c9-af85-2ba96174013b.png)
![c3](https://user-images.githubusercontent.com/108628726/210952470-4616355d-1f0e-418c-80a9-3d8ae8790da7.png)
![c4](https://user-images.githubusercontent.com/108628726/210952494-258b1ae8-b400-430c-9220-c119f90885eb.png)

2023-01-05 21:37 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @RashidMenhas

Good job working on the project so far! 
✔️ All files are putnin the right place
✔️ You added screenshots of your queries
However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/3og0IPMeREHpEV0f60/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

- [ ] Great job using the microverse README template, however, you need to customize it so that it is more professional and gives more details about your project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-05 21:37 UTC, Ghiftee commented on queries.sql
> +rollback;
- [ ] According to the requirements, kindly ensure that after each transaction, you verify that the change was made, then you roll back the change and then verify that the change was undone. e.g:

``` UPDATE animals
   SET species = 'unspecified';  - make change

   SELECT species from animals; - verify that change was made
   ROLLBACK; - rollback change

   SELECT species from animals; - verify that change was undone
```

2023-01-05 21:37 UTC, Ghiftee commented on queries.sql
> + commit;
- [ ] According to the requirements, kindly write a query which verifies that the change was made and persists after the commit. e.g

```sql
 SELECT species from animals; -- verify that change was made
   COMMIT;
   SELECT species from animals; -- verify that change persists after commit
```

2023-01-05 21:37 UTC, Ghiftee commented on queries.sql
> + rollback;
- [ ] You are currently missing this requirement - ```After the rollback verify if all records in the animals table still exists.``` Kindly implement it

2023-01-05 21:37 UTC, Ghiftee commented on queries.sql
> +  select AVG(escape_attempts) from animals where date_of_birth between '01-01-1990' and '01-01-2000' group by species;
- [ ] Great work writing all the queries so far, for this last query, the requirement states those born between 1990 and 2000. This means the query should begin from ```'01-01-1990'``` and end at ```'31-12-2000'```

2023-01-06 07:52 UTC, Tadesse-Alemayehu approved these changes
### Hi @RashidMenhas 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ST3D](https://user-images.githubusercontent.com/69077061/209420293-8e3384ab-0ec0-4570-ace6-db3b03775d97.gif)


## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅
 - [ ]  Correct GitFlow. ✅
 - [ ]  Good PR title/description. ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 21:00 UTC, merged